rootProject.name = 'cotm'

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
includeBuild('../node_modules/react-native-gradle-plugin')
include ':unityLibrary'
include ':unityLibrary:mobilenotifications.androidlib'
include ':react-native-unity'
project(':react-native-unity').projectDir = new File(rootProject.projectDir, '../node_modules/@azesmway/react-native-unity/android')
